var option1 = `
<h4>History of Nuclear Power</h4>
<p>The story of nuclear power began in the year 1905 with the discovery of Mass Energy Equivalance by Albert Einstein...... </p>`;

var option2 = `
<h4>How is Nuclear energy generated?</h4>
<p>Most of the nuclear energy in the world is generated by splitting of Uranium atoms in a process called nuclear fission...</p>`;

var option3 = `
<h4>Nuclear Fission and Fusion</h4>
<p>Fission is the splitting of a heavy, unstable nucleus into lighter nuclei, 
and fusion is the process where two light nuclei combine together...</p>`;

var option4 = `
<h4>Working of Nuclear Reactors</h4>
<p>The main job of a reactor is to house and control nuclear fission—a process where atoms split and release energy.....</p>`;

var option5 = `
<h4>Safety and Hazards</h4>
<p>While nuclear power provides clean energy, it can also be a major security and safety concern if not handled with 
safety precautions...</p>`;

var option6 = `
<h4>Future of Nuclear Energy</h4>
<p>Nuclear energy already powers 14% of the world's electricity, in the future this figure is only expected to rise with 
promising indications of controlled nuclear fusion...</p>`;